---
# Config tasks for Prometheus
- name: Ensure that config dir is present
  file:
    path: /etc/prometheus
    state: directory
    owner: "{{ prom_user }}"
    mode: 0755

- name: Ensure that Prometheus data dir is present
  file:
    path: /var/lib/prometheus/data
    state: directory
    owner: "{{ prom_user }}"
    mode: 0755

- name: Template Prometheus config file
  template:
    src: prometheus.yml.j2
    dest: "{{ config_dir }}/prometheus.yml"
    owner: "{{ prom_user }}"
