---
# install tasks for prometheus
- name: ensure user present
  user:
    name: "{{ prom_user }}"
    state: present

- name: Ensure the run dirs are present
  file:
    path: "{{ rundir }}/{{ item['name'] }}"
    state: directory
    mode: 0755
    owner: "{{ prom_user }}"
  with_items: "{{ components }}"

- name: Ensure the staging dirs are present
  file:
    path: "{{ tarball_staging_dir }}"
    state: directory
    mode: 0755

# Ugh. unarchive doesn't get remote_src,
# thanks, Obama.
# See https://github.com/ansible/ansible/issues/18897

- name: Get the src
  get_url:
    url: "{{ item['url'] }}/v{{ item['version'] }}/{{ item['name'] }}-{{ item['version'] }}.linux-amd64.tar.gz"
    dest: "{{ tarball_staging_dir }}"
  with_items: "{{ components }}"


- name: Unpack
  unarchive:
    src: "{{ tarball_staging_dir }}/{{ item.0['name'] }}-{{ item.0['version'] }}.linux-amd64.tar.gz"
    dest: "{{ rundir }}/{{ item.0['name']}}"
    remote_src: yes
    extra_opts: '--strip-components=1'
    owner: "{{ prom_user }}"
    creates: "{{ item.1 }}"
  with_subelements:
    - "{{ components }}"
    - binaries
